<html><head><title>ExceptionWrapperTest.php</title>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<link rel="stylesheet" type="text/css" href="sourcestyles.css" />
</head><body link="blue" vlink="blue">
<h3>File: C:\xampp\htdocs\game_zone\game_zone.v1.0\vendor\phpunit\phpunit\tests\unit\Framework\ExceptionWrapperTest.php</h3>
<SCRIPT>
defaultStatus = "File: C:\\xampp\\htdocs\\game_zone\\game_zone.v1.0\\vendor\\phpunit\\phpunit\\tests\\unit\\Framework\\ExceptionWrapperTest.php";
top.document.title  = "ExceptionWrapperTest.php";
</SCRIPT>
<pre><span class="default"></span><a name="1"><font size=-1>1     </font></a><span class="default">&lt;?php </span><span class="keyword">declare</span><span class="default">(strict_types=</span><span class="number">1</span><span class="default">);</span>
<a name="2"><font size=-1>2     </font></a><span class="default"></span><span class="comment">/*</span>
<a name="3"><font size=-1>3     </font></a><span class="comment"> * This file is part of PHPUnit.</span>
<a name="4"><font size=-1>4     </font></a><span class="comment"> *</span>
<a name="5"><font size=-1>5     </font></a><span class="comment"> * (c) Sebastian Bergmann &lt;sebastian@phpunit.de&gt;</span>
<a name="6"><font size=-1>6     </font></a><span class="comment"> *</span>
<a name="7"><font size=-1>7     </font></a><span class="comment"> * For the full copyright and license information, please view the LICENSE</span>
<a name="8"><font size=-1>8     </font></a><span class="comment"> * file that was distributed with this source code.</span>
<a name="9"><font size=-1>9     </font></a><span class="comment"> */</span>
<a name="10"><font size=-1>10     </font></a><span class="comment"></span><span class="keyword">namespace <a href="dictionary_P.html#136274">PHPUnit</a></span><span class="default">\Framework;</span>
<a name="11"><font size=-1>11     </font></a><span class="default"></span>
<a name="12"><font size=-1>12     </font></a><span class="default"></span><span class="comment">/**</span>
<a name="13"><font size=-1>13     </font></a><span class="comment"> * @small</span>
<a name="14"><font size=-1>14     </font></a><span class="comment"> */</span>
<a name="15"><font size=-1>15     </font></a><span class="comment"></span><span class="keyword">final class <a href="dictionary_P.html#73290">ExceptionWrapperTest</a> extends <a href="dictionary_P.html#173889">TestCase</a></span>
<a name="16"><font size=-1>16     </font></a><span class="keyword"></span><span class="default">{</span>
<a name="17"><font size=-1>17     </font></a><span class="default">    </span><span class="comment">/**</span>
<a name="18"><font size=-1>18     </font></a><span class="comment">     * @runInSeparateProcess</span>
<a name="19"><font size=-1>19     </font></a><span class="comment">     */</span>
<a name="20"><font size=-1>20     </font></a><span class="comment">    </span><span class="keyword">public function <a href="dictionary_P.html#175040">testGetOriginalException</a></span><span class="default">(): <a href="dictionary_P.html#189232">void</a></span>
<a name="21"><font size=-1>21     </font></a><span class="default">    {</span>
<a name="22"><font size=-1>22     </font></a><span class="default">        $<a href="dictionary_E.html#63209">e</a>       = </span><span class="keyword">new </span><span class="default">\<a href="dictionary_B.html#33427">BadFunctionCallException</a>(</span><span class="string">'custom class exception'</span><span class="default">);</span>
<a name="23"><font size=-1>23     </font></a><span class="default">        $<a href="dictionary_W.html#190973">wrapper</a> = </span><span class="keyword">new <a href="dictionary_P.html#73288">ExceptionWrapper</a></span><span class="default">($<a href="dictionary_E.html#63209">e</a>);</span>
<a name="24"><font size=-1>24     </font></a><span class="default"></span>
<a name="25"><font size=-1>25     </font></a><span class="default">        $this-&gt;<a href="dictionary_P.html#29960">assertInstanceOf</a>(\<a href="dictionary_B.html#33427">BadFunctionCallException</a>::</span><span class="keyword">class</span><span class="default">, $<a href="dictionary_W.html#190973">wrapper</a>-&gt;<a href="dictionary_G.html#87360">getOriginalException</a>());</span>
<a name="26"><font size=-1>26     </font></a><span class="default">    }</span>
<a name="27"><font size=-1>27     </font></a><span class="default"></span>
<a name="28"><font size=-1>28     </font></a><span class="default">    </span><span class="comment">/**</span>
<a name="29"><font size=-1>29     </font></a><span class="comment">     * @runInSeparateProcess</span>
<a name="30"><font size=-1>30     </font></a><span class="comment">     */</span>
<a name="31"><font size=-1>31     </font></a><span class="comment">    </span><span class="keyword">public function <a href="dictionary_P.html#175041">testGetOriginalExceptionWithPrevious</a></span><span class="default">(): <a href="dictionary_P.html#189232">void</a></span>
<a name="32"><font size=-1>32     </font></a><span class="default">    {</span>
<a name="33"><font size=-1>33     </font></a><span class="default">        $<a href="dictionary_E.html#63208">e</a>       = </span><span class="keyword">new </span><span class="default">\<a href="dictionary_B.html#33427">BadFunctionCallException</a>(</span><span class="string">'custom class exception'</span><span class="default">, </span><span class="number">0</span><span class="default">, </span><span class="keyword">new </span><span class="default">\<a href="dictionary_E.html#73138">Exception</a>(</span><span class="string">'previous'</span><span class="default">));</span>
<a name="34"><font size=-1>34     </font></a><span class="default">        $<a href="dictionary_W.html#190972">wrapper</a> = </span><span class="keyword">new <a href="dictionary_P.html#73288">ExceptionWrapper</a></span><span class="default">($<a href="dictionary_E.html#63208">e</a>);</span>
<a name="35"><font size=-1>35     </font></a><span class="default"></span>
<a name="36"><font size=-1>36     </font></a><span class="default">        $this-&gt;<a href="dictionary_P.html#29960">assertInstanceOf</a>(\<a href="dictionary_B.html#33427">BadFunctionCallException</a>::</span><span class="keyword">class</span><span class="default">, $<a href="dictionary_W.html#190972">wrapper</a>-&gt;<a href="dictionary_G.html#87360">getOriginalException</a>());</span>
<a name="37"><font size=-1>37     </font></a><span class="default">    }</span>
<a name="38"><font size=-1>38     </font></a><span class="default"></span>
<a name="39"><font size=-1>39     </font></a><span class="default">    </span><span class="comment">/**</span>
<a name="40"><font size=-1>40     </font></a><span class="comment">     * @runInSeparateProcess</span>
<a name="41"><font size=-1>41     </font></a><span class="comment">     */</span>
<a name="42"><font size=-1>42     </font></a><span class="comment">    </span><span class="keyword">public function <a href="dictionary_P.html#175881">testNoOriginalExceptionInStacktrace</a></span><span class="default">(): <a href="dictionary_P.html#189232">void</a></span>
<a name="43"><font size=-1>43     </font></a><span class="default">    {</span>
<a name="44"><font size=-1>44     </font></a><span class="default">        $<a href="dictionary_E.html#63207">e</a>       = </span><span class="keyword">new </span><span class="default">\<a href="dictionary_B.html#33427">BadFunctionCallException</a>(</span><span class="string">'custom class exception'</span><span class="default">);</span>
<a name="45"><font size=-1>45     </font></a><span class="default">        $<a href="dictionary_W.html#190971">wrapper</a> = </span><span class="keyword">new <a href="dictionary_P.html#73288">ExceptionWrapper</a></span><span class="default">($<a href="dictionary_E.html#63207">e</a>);</span>
<a name="46"><font size=-1>46     </font></a><span class="default"></span>
<a name="47"><font size=-1>47     </font></a><span class="default">        </span><span class="comment">// Replace the only mention of &quot;BadFunctionCallException&quot; in wrapper</span>
<a name="48"><font size=-1>48     </font></a><span class="comment">        </span><span class="default">$<a href="dictionary_W.html#190971">wrapper</a>-&gt;<a href="dictionary_S.html#155626">setClassName</a>(</span><span class="string">'MyException'</span><span class="default">);</span>
<a name="49"><font size=-1>49     </font></a><span class="default"></span>
<a name="50"><font size=-1>50     </font></a><span class="default">        $<a href="dictionary_D.html#57334">data</a> = \<a href="dictionary_P.html#138519">print_r</a>($<a href="dictionary_W.html#190971">wrapper</a>, <a href="dictionary_T.html#181186">true</a>);</span>
<a name="51"><font size=-1>51     </font></a><span class="default"></span>
<a name="52"><font size=-1>52     </font></a><span class="default">        $this-&gt;<a href="dictionary_P.html#30220">assertStringNotContainsString</a>(</span>
<a name="53"><font size=-1>53     </font></a><span class="default">            </span><span class="string">'BadFunctionCallException'</span><span class="default">,</span>
<a name="54"><font size=-1>54     </font></a><span class="default">            $<a href="dictionary_D.html#57334">data</a>,</span>
<a name="55"><font size=-1>55     </font></a><span class="default">            </span><span class="string">'Assert there is s no other BadFunctionCallException mention in stacktrace'</span>
<a name="56"><font size=-1>56     </font></a><span class="string">        </span><span class="default">);</span>
<a name="57"><font size=-1>57     </font></a><span class="default">    }</span>
<a name="58"><font size=-1>58     </font></a><span class="default">}</span>
<a name="59"><font size=-1>59     </font></a><span class="default"></span>
</pre></body></html>
